### ISSUE TITLE
window.$zopim is not initialized

### ISSUE THREAD

**Issue by Prizrack13** [wittawasw/zopim_rails#4]
In new version of this gem variable window.$zopim is not initialized.

$zopim used to define name, show chat and etc

**Comment by Prizrack13** [comment]
Looks like you change javascript code in v0.0.3 . So I will still use 0.0.2

**Comment by wittawasw** [comment]
Fixed it. https://github.com/wittawasw/zopim_rails/commit/191a341f9dc5ec1e65f12944df56fe1cfe0e601a 
I'm generally not using this anymore, thank for letting me know.
