### ISSUE TITLE
Chat lost in between page load through turbolinks

### ISSUE THREAD

**Issue by thcottin** [wittawasw/zopim_rails#5]
Hi,
I encountered a problem using the gem with turbolinks. When I click on a turbolinks-enabled link, the widget appears after the new page load, which is great, but it does not maintain the current chat history and worse, creates a new visitor in Zopim dashboard.

Any idea how to fix this issue?

Thanks for your help

**Comment by wittawasw** [comment]
Does it maintain chat history when loading page without Turbolinks ?
I've never thought about this as an issue before since I understand that it will load new session every time we load a new page anyway.

**Comment by wittawasw** [comment]
I will close this for now since I don't think it's an issue.

**Comment by thcottin** [comment]
Yes it does maintain chat history without turbolinks, but the biggest pain is for the operator. Everytime the user clicks a link, the conversation stops and a new visitor is recreated (zopim side). It is enough of an issue that I will stop using Zopim entirely.

**Comment by eveevans** [comment]
Hi @thcottin  I dont use this gem, but there is no problem with this. I guess you are testing your application on localhost. When it becomes on production (A.K.A online) , there is no problems with this, and the conversation maintains between pages :)

**Comment by wittawasw** [comment]
@eveevans  thanks for your info, I'll open this in a meantime before I check it myself. I'm not maintaining any sites using this gem right now.

**Comment by eveevans** [comment]
Ok, but you should close this Issue.

**Comment by thcottin** [comment]
@eveevans how would you know since you dont use the gem?? I'm lucid enough to make the difference btn localhost and prod. Anyway I ended up not using this gem so you can close this issue

**Comment by eveevans** [comment]
sorry @thcottin , I was poking to @wittawasw , not you. 
Thanks anyway.

**Comment by geekvijay** [comment]
hey @thcottin have you successfully implemented zopim with turbolinks ?
I am also looking for the solution for the same.

**Comment by luizpicolo** [comment]
Hello @geekvijay.

This problema was fixed #1
