### ISSUE TITLE
Zopim does not appear

### ISSUE THREAD

**Issue by frednovack** [wittawasw/zopim_rails#9]
I have zopim implemented on my Rails application for a while. It always worked fine... when all of a sudden Zopim stopped working, it doesn't appear at all! It doesn't show or log any error. When we checkout  previous commits of the application where zopim was working fine, Zopim doesn't appear! None of my commits seems to have zopim working.

**Comment by luizpicolo** [comment]
Hello @frednovack 

I do not know what might be happening. In the latter commits #8  the gem is working. Its is can be visualized in this example https://zopimrailstest.herokuapp.com
